version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: gps-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: gps-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/gps_tracker_db
      - JWT_SECRET=your_secret_key
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gps-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_MAPBOX_TOKEN=your_mapbox_token

volumes:
  mongo-data:
